baseURL = 'https://www.cvennevik.no/'
languageCode = 'en-us'
title = 'Cecilie Vennevik'
theme = 'beautiful-hugo'

# Example config available at themes/beautiful-hugo/exampleSite/config.toml

[Params]
  homeTitle = "Blog"
  rss = true

[Author]
  name = "Cecilie Vennevik"
  twitter = "cvennevik"
  mastodon = "https://hachyderm.io/@cvennevik"
